// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    SolarSystem: typeof import('./components/SolarSystem.vue')['default']
    SolarSystem1: typeof import('./components/SolarSystem1.vue')['default']
    SolarSystem2: typeof import('./components/SolarSystem2.vue')['default']
  }
}

export { }
